# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geolocation', '0003_country_group'),
        ('tournament', '0002_auto_20180527_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo')),
                ('privacity_status', models.CharField(choices=[('privado', 'PRIVADO'), ('publico', 'PUBLICO')], max_length=20)),
                ('score_status', models.CharField(choices=[('marcador', 'marcador'), ('ganador', 'GANADOR')], max_length=20)),
                ('bet_status', models.CharField(choices=[('dinero', 'DINERO'), ('reto', 'RETO')], max_length=20)),
                ('rode', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('challenge', models.TextField(blank=True, null=True)),
                ('score_favor', models.IntegerField(blank=True, null=True)),
                ('score_against', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.Country')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.Match')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuestas',
            },
        ),
    ]
