# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='players.Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
