# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20180527_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Posición', 'verbose_name_plural': 'Posiciones'},
        ),
    ]
