# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20180527_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='overall',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
