# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20180527_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
