# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20180527_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.URLField()),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.RenameField(
            model_name='player',
            old_name='aceleration',
            new_name='acceleration',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='club_name',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='order',
            new_name='order_fifa',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='reactions',
            new_name='potential',
        ),
        migrations.RemoveField(
            model_name='player',
            name='born_country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technicaldirector',
            name='born_date',
        ),
        migrations.AddField(
            model_name='player',
            name='reaction',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicaldirector',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country'),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Club'),
        ),
    ]
