# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20180527_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.AddField(
            model_name='player',
            name='club_logo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='club_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
