# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField()),
                ('matchday', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in progress', 'En progreso'), ('finished', 'Terminado')], max_length=20)),
                ('country_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_1', to='geolocation.Country')),
                ('country_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_2', to='geolocation.Country')),
            ],
            options={
                'verbose_name': 'Partido',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('city', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estadio',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Stadium'),
        ),
    ]
