# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_country_group'),
        ('tournament', '0002_auto_20180527_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='runnerup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runnerup', to='geolocation.Country'),
        ),
        migrations.AddField(
            model_name='groups',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='geolocation.Country'),
        ),
    ]
