# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
