# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180527_0040'),
        ('geolocation', '0002_country_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Groups'),
        ),
    ]
